/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.85 95/04/24 10:48:47 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 102
#define YY_END_OF_BUFFER 103
static yyconst short int yy_accept[239] =
    {   0,
        0,    0,   82,   82,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  103,  102,   25,   88,   81,  102,
       30,  102,   83,   21,   22,    3,    1,   27,    2,   66,
        4,   32,   31,   26,   12,    5,   10,  102,   70,   19,
       20,   71,   71,   71,   71,   71,   71,   71,   71,   71,
       71,   63,   71,   71,   71,   71,   71,   23,  102,   24,
       82,   76,  102,   84,   87,  102,   89,  101,  102,   67,
       69,   15,   72,   72,   18,    8,    0,   32,   31,    6,
        7,   29,   32,    9,   32,    0,    0,    0,    0,   31,
       13,   16,    0,   11,    0,   73,   73,   70,   71,   71,

       71,   71,   71,   45,   71,   71,   71,   71,   71,   46,
       50,   71,   71,   56,   71,   71,   71,   71,   71,   71,
       71,   71,   71,   17,   82,   76,   78,   78,    0,   84,
       85,   86,   89,   92,   93,   90,  100,   99,   98,   97,
       91,   96,   94,   95,   67,   69,   72,   72,   28,    0,
       32,   33,   35,   33,   14,    0,   74,   74,   73,   73,
       57,   71,   71,   68,   71,   52,   71,   43,   71,   36,
       39,   71,   71,   71,   71,   71,   71,   71,   71,   71,
       71,   71,   78,   78,   79,    0,   90,    0,   74,   74,
       71,   71,   48,   71,   71,   61,   71,   71,   71,   71,

       65,   62,   71,   37,   71,   44,   47,   71,   71,   79,
       80,   77,   90,    0,   51,   59,   49,   38,   60,   71,
       71,   71,   71,   40,   42,   41,   80,   75,   64,   71,
       71,   54,   53,   55,   71,   71,   58,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    4,    5,    6,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
       20,   20,   20,   20,   20,   21,   21,   22,    1,   23,
       24,   25,    1,   26,   27,   27,   27,   27,   28,   27,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   30,   29,   29,
       31,   32,   33,    1,   34,    1,   35,   36,   37,   38,

       39,   40,   41,   42,   43,   34,   44,   45,   34,   46,
       47,   48,   34,   49,   50,   51,   52,   53,   54,   55,
       56,   34,   57,   58,   59,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[60] =
    {   0,
        1,    2,    1,    3,    1,    1,    1,    1,    4,    1,
        1,    1,    1,    1,    1,    1,    1,    5,    5,    5,
        5,    1,    1,    6,    1,    7,    8,    8,    8,    8,
        1,    9,    1,    8,   10,   10,   10,   10,   10,   10,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    1,    1,    1
    } ;

static yyconst short int yy_base[265] =
    {   0,
        0,    0,  555,  554,  531,  530,   51,   52,   60,   61,
       60,   83,  106,    0,  542,  558,  516,  558,  558,   39,
      558,  531,  558,  558,  558,  512,   54,  558,   61,   70,
      510,  147,  153,  558,  509,  140,  496,  161,    0,  558,
      558,    0,  133,  469,  131,  139,  158,  478,  154,  152,
      465,  149,  473,  157,  155,  465,  466,  558,  447,  558,
        0,    0,  179,    0,  558,  197,    0,  558,  226,    0,
        0,  558,    0,    0,  558,  558,  192,  203,  220,  558,
      558,  488,  232,  558,  262,  273,  236,  189,    0,  279,
      478,  558,  463,  558,  187,    0,    0,    0,    0,  461,

      448,  457,  453,    0,  441,  452,  442,  436,  433,    0,
        0,  436,  428,    0,  185,  198,  427,  430,  421,  429,
      413,  409,  399,  558,    0,    0,  268,  287,  382,    0,
      558,  558,    0,  558,  558,  294,  558,  558,  558,  558,
      558,  558,  558,  558,    0,    0,    0,    0,  558,  301,
      309,  313,  207,    0,  558,  384,    0,    0,    0,    0,
        0,  388,  387,    0,  194,    0,  369,    0,  367,    0,
        0,  174,  365,  368,  237,  357,  315,  315,  307,  313,
      308,  305,  294,  300,  307,  311,  317,  305,    0,    0,
      291,  302,    0,  305,  305,    0,  273,  282,  269,  263,

        0,    0,  256,    0,  255,    0,    0,  240,  237,  323,
      340,  558,  558,  227,    0,    0,    0,    0,  229,  217,
      230,  228,  197,    0,    0,    0,  341,  558,    0,  141,
       36,    0,    0,    0,   37,   33,    0,  558,  357,  367,
      377,  387,  397,  400,  404,  410,  416,  426,  436,  446,
      456,  466,  472,  478,  484,  490,  496,  499,  505,  511,
      521,  527,  533,  543
    } ;

static yyconst short int yy_def[265] =
    {   0,
      238,    1,  239,  239,  240,  240,  241,  241,  242,  242,
      243,  243,  243,   13,  238,  238,  238,  238,  238,  244,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  245,  246,  238,
      238,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  238,  238,  238,
      248,  249,  250,  251,  238,  238,  252,  238,  238,  253,
      254,  238,  255,  256,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  257,  238,
      238,  238,  238,  238,  258,  259,  260,  246,  247,  247,

      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  238,  248,  249,  238,  250,  261,  251,
      238,  238,  252,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  253,  254,  255,  256,  238,  238,
      238,  238,  238,  257,  238,  238,  262,  263,  259,  260,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  238,  238,  238,  264,  238,  238,  262,  263,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,

      247,  247,  247,  247,  247,  247,  247,  247,  247,  238,
      238,  238,  238,  238,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  238,  238,  247,  247,
      247,  247,  247,  247,  247,  247,  247,    0,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238
    } ;

static yyconst short int yy_nxt[618] =
    {   0,
       16,   16,   17,   18,   19,   20,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   30,   31,   32,   33,   33,
       33,   34,   35,   36,   37,   38,   39,   39,   39,   39,
       40,   16,   41,   42,   43,   44,   42,   45,   46,   47,
       48,   42,   49,   42,   42,   50,   51,   52,   53,   54,
       55,   56,   42,   57,   42,   42,   58,   59,   60,   65,
       65,   16,   16,   68,   68,   73,   73,   73,   73,   77,
      237,   78,   79,   79,   79,  236,   77,   80,   78,   79,
       79,   79,   66,   66,   81,   82,  235,   83,   83,   83,
       83,   69,   69,   70,   70,   70,   70,   70,   70,   70,

       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   71,
       71,   71,   71,   71,   71,   71,   71,   71,   71,   71,
       71,   71,   71,   71,   71,   71,   71,   71,   71,   71,
       71,   71,   77,   92,   85,   85,   85,   78,   77,  103,
       90,   90,   90,   90,   86,   93,   87,  104,  100,  234,
       86,  101,   88,  105,  106,   86,   95,   96,   96,   96,
       96,   86,  107,  110,  112,  118,  120,  115,  113,  111,

      116,   89,  128,  121,  108,  131,  153,  153,  119,   83,
       83,   83,   83,  157,  157,  157,  157,  129,   77,  197,
       78,   78,   78,   78,  153,  153,  198,  172,  132,  134,
       86,  173,  193,  174,  135,   77,  194,   90,   90,   90,
       90,   86,  233,  136,  136,  136,  136,   86,  175,   83,
       83,   83,   83,  152,  152,  152,  152,  137,   86,   86,
      138,  139,  152,  152,  232,  140,  231,  230,  229,  183,
       86,  141,  228,  201,  142,  226,  143,   77,  144,   85,
       85,   85,   78,  183,  225,  150,  202,  150,  184,   86,
      151,  151,  151,  151,   77,  183,   90,   90,   90,   90,

       86,  183,  184,  224,  223,  222,   86,  221,  210,  183,
      128,  187,  187,  187,  187,  183,  220,   86,  151,  151,
      151,  151,  210,  219,  210,  129,  151,  151,  151,  151,
      152,  152,  152,  152,  213,  213,  213,  213,  210,  152,
      152,  227,  227,  218,  217,  216,  215,  214,  212,  209,
      208,  207,  206,  205,  204,  227,  227,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   64,   64,   64,
       64,   64,   64,   64,   64,   64,   64,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   16,   16,   16,

       16,   16,   16,   16,   16,   16,   16,   74,  203,   74,
       97,   97,  200,   97,   98,  199,  196,   98,  195,   98,
       99,  192,  191,   99,  188,   99,  125,  186,  125,  125,
      125,  125,  125,  125,  125,  125,  126,  126,  126,  126,
      126,  182,  126,  126,  126,  126,  127,  127,  127,  127,
      127,  127,  127,  127,  127,  127,  130,  130,  130,  181,
      130,  130,  130,  130,  180,  130,  133,  179,  178,  133,
      133,  133,  133,  133,  177,  133,  145,  176,  171,  145,
      170,  145,  146,  169,  168,  146,  167,  146,  147,  166,
      165,  147,  164,  147,  148,  163,  162,  148,  161,  148,

      154,  156,  155,  149,  124,  154,  158,  123,  158,  159,
      122,  117,  159,  114,  159,  160,  109,  102,  160,   94,
      160,  185,  185,  185,  185,  185,  185,  185,  185,  185,
      185,  189,   91,   84,  189,   76,  189,  190,   75,   72,
      190,  238,  190,  211,  211,  211,  211,  211,  211,  211,
      211,  211,  211,   63,   63,   16,   16,   15,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,

      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238
    } ;

static yyconst short int yy_chk[618] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    7,
        8,    9,   10,    9,   10,   20,   20,   20,   20,   27,
      236,   27,   27,   27,   27,  235,   29,   27,   29,   29,
       29,   29,    7,    8,   29,   30,  231,   30,   30,   30,
       30,    9,   10,   11,   11,   11,   11,   11,   11,   11,

       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   32,   36,   32,   32,   32,   32,   33,   45,
       33,   33,   33,   33,   32,   36,   32,   45,   43,  230,
       33,   43,   32,   46,   46,   32,   38,   38,   38,   38,
       38,   33,   47,   49,   50,   54,   55,   52,   50,   49,

       52,   32,   63,   55,   47,   66,   88,   88,   54,   77,
       77,   77,   77,   95,   95,   95,   95,   63,   78,  172,
       78,   78,   78,   78,  153,  153,  172,  115,   66,   69,
       78,  115,  165,  116,   69,   79,  165,   79,   79,   79,
       79,   78,  223,   69,   69,   69,   69,   79,  116,   83,
       83,   83,   83,   87,   87,   87,   87,   69,   79,   83,
       69,   69,   87,   87,  222,   69,  221,  220,  219,  127,
       83,   69,  214,  175,   69,  209,   69,   85,   69,   85,
       85,   85,   85,  127,  208,   86,  175,   86,  128,   85,
       86,   86,   86,   86,   90,  183,   90,   90,   90,   90,

       85,  184,  128,  205,  203,  200,   90,  199,  185,  183,
      128,  136,  136,  136,  136,  184,  198,   90,  150,  150,
      150,  150,  185,  197,  210,  128,  151,  151,  151,  151,
      152,  152,  152,  152,  187,  187,  187,  187,  210,  152,
      152,  211,  227,  195,  194,  192,  191,  188,  186,  182,
      181,  180,  179,  178,  177,  211,  227,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  240,  240,  240,
      240,  240,  240,  240,  240,  240,  240,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  243,  243,  243,

      243,  243,  243,  243,  243,  243,  243,  244,  176,  244,
      245,  245,  174,  245,  246,  173,  169,  246,  167,  246,
      247,  163,  162,  247,  156,  247,  248,  129,  248,  248,
      248,  248,  248,  248,  248,  248,  249,  249,  249,  249,
      249,  123,  249,  249,  249,  249,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  251,  251,  251,  122,
      251,  251,  251,  251,  121,  251,  252,  120,  119,  252,
      252,  252,  252,  252,  118,  252,  253,  117,  113,  253,
      112,  253,  254,  109,  108,  254,  107,  254,  255,  106,
      105,  255,  103,  255,  256,  102,  101,  256,  100,  256,

      257,   93,   91,   82,   59,  257,  258,   57,  258,  259,
       56,   53,  259,   51,  259,  260,   48,   44,  260,   37,
      260,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  262,   35,   31,  262,   26,  262,  263,   22,   17,
      263,   15,  263,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264,    6,    5,    4,    3,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,

      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
char *yytext;
#line 1 "lexic.flex"
#define INITIAL 0
#line 2 "lexic.flex"

#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <locale.h>

int _int;                   //output int
float _float;               //output float
char tmp[100];              // для перевода числа из двоичной в десятичную систему счисления
int len;                    // strings length
int i;                      // counter
char tmp[100] = "";         // для перевода числа из двоичной в десятичную систему счисления
char comment[10000] = "";   // comment
char text[10000] = "";      // comment
char strings[1000] = "";	// for output
char s[2];
#define YY_NEVER_INTERACTIVE 1
#define ONE_COMMENT 1

#define MANY_COMMENTS 2

#define SIMPLE_STRING 3

#define DIF_STRING 4

#define METHOD 5

#define METHOD_NAME 6

#line 614 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 34 "lexic.flex"


#line 764 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 239 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 558 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 36 "lexic.flex"
printf("Операция: %s\n", yytext);
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 37 "lexic.flex"
printf("Операция: %s\n", yytext);	
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 38 "lexic.flex"
printf("Операция: %s\n", yytext);
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 39 "lexic.flex"
printf("Операция: %s\n", yytext);
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 40 "lexic.flex"
printf("Операция: %s\n", yytext);
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 41 "lexic.flex"
printf("Операция: %s\n", yytext);
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 42 "lexic.flex"
printf("Операция: %s\n", yytext);
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 43 "lexic.flex"
printf("Операция: %s\n", yytext);
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 44 "lexic.flex"
printf("Операция: %s\n", yytext);
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 45 "lexic.flex"
printf("Операция: %s\n", yytext);
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 46 "lexic.flex"
printf("Операция: %s\n", yytext);
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 47 "lexic.flex"
printf("Операция: %s\n", yytext);
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 48 "lexic.flex"
printf("Операция: %s\n", yytext); 
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 49 "lexic.flex"
printf("Операция: %s\n", yytext);
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 50 "lexic.flex"
printf("Операция: %s\n", yytext);
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 51 "lexic.flex"
printf("Операция: %s\n", yytext);
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 52 "lexic.flex"
printf("Операция: %s\n", yytext);
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 53 "lexic.flex"
printf("Операция: %s\n", yytext);
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 54 "lexic.flex"
printf("Операция: %s\n", yytext);
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 55 "lexic.flex"
printf("Операция: %s\n", yytext);
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 56 "lexic.flex"
printf("Операция: %s\n", yytext);
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 57 "lexic.flex"
printf("Операция: %s\n", yytext);
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 58 "lexic.flex"
printf("Операция: %s\n", yytext);
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 59 "lexic.flex"
printf("Операция: %s\n", yytext);
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 60 "lexic.flex"
printf("Операция: %s\n", yytext);
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 61 "lexic.flex"
printf("Операция: %s\n", yytext);
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 62 "lexic.flex"
printf("Операция: %s\n", yytext);
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 63 "lexic.flex"
printf("Операция: %s\n", yytext);
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 64 "lexic.flex"
printf("Операция: %s\n", yytext);
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 65 "lexic.flex"
printf("Операция: %s\n", yytext);
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 67 "lexic.flex"
printf("Целочисленная константа: %s \n", yytext);
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 69 "lexic.flex"
{
	sscanf(yytext, "%g", &_float);
	printf("Дробная константа: %g \n", _float);
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 74 "lexic.flex"
{
	sscanf(yytext, "%x", &_int);
	printf("Шестнадцатеричная константа: %d \n", _int);
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 79 "lexic.flex"
{
	sscanf(yytext, "%o", &_int);
	printf("Восьмеричная константа: %d \n", _int);
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 84 "lexic.flex"
{
	tmp[0] = 0;
	_int= 0;

    strcat(tmp, &yytext[2]);
    len = strlen(tmp);
    for(i = 0; i < len; i++) {
    	if(tmp[i] == '1') {
    		_int += 1 << len -1 -i;
        }
    }
    printf("Двоичная константа: %d \n", _int);
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 98 "lexic.flex"
printf("Ключевое слово: %s\n", yytext);
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 99 "lexic.flex"
printf("Ключевое слово: %s\n", yytext);
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 100 "lexic.flex"
printf("Ключевое слово: %s\n", yytext);
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 101 "lexic.flex"
printf("Ключевое слово: %s\n", yytext);
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 102 "lexic.flex"
printf("Ключевое слово: %s\n", yytext);
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 103 "lexic.flex"
printf("Ключевое слово: %s\n", yytext);
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 104 "lexic.flex"
printf("Ключевое слово: %s\n", yytext);
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 105 "lexic.flex"
printf("Ключевое слово: %s\n", yytext);
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 106 "lexic.flex"
printf("Ключевое слово: %s\n", yytext);
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 107 "lexic.flex"
printf("Ключевое слово: %s\n", yytext);
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 108 "lexic.flex"
printf("Ключевое слово: %s\n", yytext);
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 109 "lexic.flex"
printf("Ключевое слово: %s\n", yytext);
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 110 "lexic.flex"
printf("Ключевое слово: %s\n", yytext);
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 111 "lexic.flex"
printf("Ключевое слово: %s\n", yytext);
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 112 "lexic.flex"
printf("Ключевое слово: %s\n", yytext);
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 113 "lexic.flex"
printf("Ключевое слово: %s\n", yytext);
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 114 "lexic.flex"
printf("Ключевое слово: %s\n", yytext);
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 115 "lexic.flex"
printf("Ключевое слово: %s\n", yytext);
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 116 "lexic.flex"
printf("Ключевое слово: %s\n", yytext);
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 117 "lexic.flex"
printf("Ключевое слово: %s\n", yytext);
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 118 "lexic.flex"
printf("Ключевое слово: %s\n", yytext);
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 119 "lexic.flex"
printf("Ключевое слово: %s\n", yytext);
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 120 "lexic.flex"
printf("Ключевое слово: %s\n", yytext);
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 121 "lexic.flex"
printf("Ключевое слово : %s\n", yytext);
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 123 "lexic.flex"
printf("Метод для работы с консолью: %s\n", yytext);
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 124 "lexic.flex"
printf("Метод для работы с консолью: %s\n", yytext);
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 125 "lexic.flex"
printf("Метод для работы с консолью: %s\n", yytext);
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 126 "lexic.flex"
printf("Метод для работы с консолью: %s\n", yytext);
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 127 "lexic.flex"
printf("Метод для работы с консолью: %s\n", yytext);
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 128 "lexic.flex"
printf("Метод для работы с консолью: %s\n", yytext);
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 130 "lexic.flex"
BEGIN(METHOD); 
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 131 "lexic.flex"
{
	printf("Метод: %s\n", yytext);
	BEGIN(INITIAL);
}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 136 "lexic.flex"
BEGIN(METHOD_NAME); 
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 137 "lexic.flex"
{
    printf("Ключевое слово: def\n");
	printf("Метод: %s\n", yytext);
	BEGIN(INITIAL);
}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 143 "lexic.flex"
{
	strcpy(text, yytext);
	printf("Константа: %s\n", text);
}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 148 "lexic.flex"
{
	strcpy(text, yytext);
	printf("Переменная: %s\n", text);
}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 153 "lexic.flex"
{
	strcpy(text, &yytext[1]);
	printf("Глобальная переменная: %s\n", text);
}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 158 "lexic.flex"
{
	strcpy(text, &yytext[1]);
	printf("Переменная объекта: %s\n", text);
}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 163 "lexic.flex"
{
	strcpy(text, &yytext[2]);
	printf("Переменная класса: %s\n", text);
}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 168 "lexic.flex"
BEGIN(MANY_COMMENTS); 
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 169 "lexic.flex"
{
	strcat(comment, yytext);
}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 173 "lexic.flex"
{
	strcat(comment,yytext);
	comment[strlen(comment)-4] = 0;
	printf("Многострочный комментарий: %s\n",comment);
	comment[0] = 0;
	BEGIN(INITIAL);
}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 181 "lexic.flex"
{
    strcat(comment, yytext);
}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 185 "lexic.flex"
{
    strcat(comment, yytext);
}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 189 "lexic.flex"
{
    strcat(comment, yytext);
}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 193 "lexic.flex"
BEGIN(ONE_COMMENT);
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 194 "lexic.flex"
{
	strcat(comment, yytext); 
	printf("Однострочный комментарий: %s",comment);
	comment[0] = 0;
	BEGIN(INITIAL);
}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 201 "lexic.flex"
{
	BEGIN(SIMPLE_STRING);
}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 205 "lexic.flex"
{
    strcat(strings, yytext);
}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 209 "lexic.flex"
{
	strcat(strings, "'");
}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 213 "lexic.flex"
{
    strcat(strings, "\\");
}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 217 "lexic.flex"
{
	printf("Строковая константа: %s\n", strings);
    strings[0] = 0;
	BEGIN(INITIAL); 
}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 223 "lexic.flex"
{
	BEGIN(DIF_STRING); 
}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 227 "lexic.flex"
{
	strcat(strings, yytext);
}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 231 "lexic.flex"
{
	s[0]=atoi(&*(yytext+1));
	s[1]=0;
	strcat(strings, s);
}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 237 "lexic.flex"
{
	strcat(strings, "\n");
}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 240 "lexic.flex"
{
	strcat(strings, "\"");
}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 243 "lexic.flex"
{
	strcat(strings, "\'");
}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 246 "lexic.flex"
{
	strcat(strings, "\t");
}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 249 "lexic.flex"
{
	strcat(strings, "\t");
}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 252 "lexic.flex"
{
	strcat(strings, "\r");
}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 255 "lexic.flex"
{
	strcat(strings, "\f");
}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 258 "lexic.flex"
{
	strcat(strings, "\b");
}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 261 "lexic.flex"
{
	strcat(strings, "\a");
}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 264 "lexic.flex"
{
	strcat(strings, "\\");
}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 267 "lexic.flex"
{
	printf("Строковая константа: %s\n", strings);
    strings[0] = 0;
	BEGIN(INITIAL);
}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 273 "lexic.flex"
ECHO;
	YY_BREAK
#line 1463 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(ONE_COMMENT):
case YY_STATE_EOF(MANY_COMMENTS):
case YY_STATE_EOF(SIMPLE_STRING):
case YY_STATE_EOF(DIF_STRING):
case YY_STATE_EOF(METHOD):
case YY_STATE_EOF(METHOD_NAME):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a singled characater, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 239 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 239 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 238);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yytext_ptr = yy_c_buf_p;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						{
						yy_c_buf_p =
						yytext_ptr + YY_MORE_ADJ;
						return EOF;
						}

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;
					break;

				case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
					YY_FATAL_ERROR(
					"unexpected last match in yyinput()" );
#else
					YY_FATAL_ERROR(
					"unexpected last match in input()" );
#endif
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *str )
#else
YY_BUFFER_STATE yy_scan_string( str )
yyconst char *str;
#endif
	{
	int len;
	for ( len = 0; str[len]; ++len )
		;

	return yy_scan_bytes( str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n - YY_MORE_ADJ; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 273 "lexic.flex"


int main(int argc, char* argv[]) {
	setlocale(LC_CTYPE, ".1251");
	yyin = fopen("test.txt", "r");
	yylex();
	fclose(yyin);
	system("pause");
    return 0;
}