/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.85 95/04/24 10:48:47 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT

#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 98
#define YY_END_OF_BUFFER 99
static yyconst short int yy_acclist[283] =
    {   0,
       76,   76,   99,   98,    1,   98,   27,   98,   82,   98,
       75,   98,   98,   98,   77,   98,   23,   98,   24,   98,
        5,   98,    2,   98,   29,   98,    4,   98,    3,   98,
        6,   98,   32,   36,   98,   33,   98,   28,   98,   14,
       98,    7,   98,   12,   98,   98,   64,   98,   21,   98,
       22,   98,   65,   98,   65,   98,   65,   98,   65,   98,
       65,   98,   65,   98,   65,   98,   65,   98,   65,   98,
       65,   98,   63,   65,   98,   65,   98,   65,   98,   65,
       98,   65,   98,   65,   98,   25,   98,   98,   26,   98,
       76,   98,   70,   98,   98,   78,   98,   81,   98,   98,

       83,   98,   96,   98,   83,   98,   98,   17,   66,   66,
       20,   10,   33,    8,    9,   31,   34,   11,   36,   33,
       97,   15,   18,   13,   67,   67,   64,   65,   65,   65,
       65,   65,   47,   65,   65,   65,   65,   65,   48,   65,
       50,   65,   65,   65,   55,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   65,   19,   76,   70,   71,   71,
       78,   79,   80,   83,   83,   87,   88,   84,   84,   95,
       94,   93,   92,   86,   91,   89,   90,   66,   66,   30,
       35,   37,   35,   16,   68,   68,   67,   67,   56,   65,
       65,   65,   39,   65,   65,   51,   65,   65,   45,   65,

       38,   65,   41,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   71,   71,   72,   83,   85,   84,
       34,   68,   68,   65,   65,   49,   65,   65,   65,   65,
       65,   65,   65,   40,   65,   65,   46,   65,   61,   65,
       65,   65,   72,   73,   74,   83,   85,   84,   85,   58,
       65,   59,   65,   60,   65,   62,   65,   65,   65,   65,
       65,   42,   65,   44,   65,   43,   65,   73,   85,   69,
       65,   65,   53,   65,   52,   65,   54,   65,   65,   65,
       57,   65
    } ;

static yyconst short int yy_accept[236] =
    {   0,
        1,    1,    1,    2,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    4,    5,    7,    9,   11,
       13,   14,   15,   17,   19,   21,   23,   25,   27,   29,
       31,   33,   36,   38,   40,   42,   44,   46,   47,   49,
       51,   53,   55,   57,   59,   61,   63,   65,   67,   69,
       71,   73,   76,   78,   80,   82,   84,   86,   88,   89,
       91,   93,   95,   96,   98,  100,  101,  103,  105,  107,
      108,  109,  110,  111,  112,  113,  113,  113,  114,  115,
      116,  117,  118,  119,  120,  120,  120,  120,  121,  122,
      123,  124,  124,  125,  125,  126,  127,  128,  129,  130,

      131,  132,  133,  135,  136,  137,  138,  139,  141,  143,
      144,  145,  147,  148,  149,  150,  151,  152,  153,  154,
      155,  156,  157,  158,  159,  160,  161,  161,  162,  163,
      164,  165,  166,  167,  168,  169,  170,  171,  172,  173,
      174,  175,  176,  177,  178,  179,  180,  181,  181,  182,
      183,  184,  185,  185,  186,  187,  188,  189,  191,  192,
      193,  195,  196,  198,  199,  201,  203,  205,  206,  207,
      208,  209,  210,  211,  212,  213,  214,  215,  216,  217,
      218,  218,  220,  221,  221,  221,  222,  222,  223,  224,
      225,  226,  228,  229,  230,  231,  232,  233,  234,  236,

      237,  239,  241,  242,  243,  244,  245,  246,  248,  249,
      250,  250,  252,  254,  256,  258,  259,  260,  261,  262,
      264,  266,  268,  269,  270,  271,  272,  273,  275,  277,
      279,  280,  281,  283,  283
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    4,    5,    6,    1,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       19,   19,   19,   19,   19,   20,   20,   21,    1,   22,
       23,   24,    1,   25,   26,   26,   26,   26,   27,   26,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   29,   28,   28,
       30,   31,   32,    1,   33,    1,   34,   35,   36,   37,

       38,   39,   40,   41,   42,   33,   43,   44,   33,   45,
       46,   47,   33,   48,   49,   50,   51,   52,   53,   54,
       33,   33,   55,   56,   57,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[58] =
    {   0,
        1,    2,    1,    3,    1,    1,    1,    4,    1,    1,
        1,    1,    1,    1,    1,    1,    5,    5,    5,    5,
        1,    1,    6,    1,    7,    8,    8,    8,    8,    1,
        9,    1,    8,   10,   10,   10,   10,   10,   10,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    1,    1,    1
    } ;

static yyconst short int yy_base[261] =
    {   0,
        0,    0,  478,  477,  455,  454,   50,   51,   58,   59,
        0,    0,    0,    0,  476,  481,  481,  451,  481,  481,
       38,  466,  481,  481,  481,  449,   54,  481,   68,   77,
      448,   83,   89,  447,  444,   45,  443,   88,    0,  481,
      481,    0,  420,  404,  406,   32,   66,   59,   80,   78,
      401,   75,  408,   83,   81,  399,  402,  481,  374,  481,
        0,    0,   61,    0,  481,  119,    0,  481,  399,  147,
      481,    0,    0,  481,  481,  113,  121,  127,  481,  481,
      412,  141,  481,  152,  157,  131,    0,  170,  481,  400,
      481,  384,  481,  174,    0,    0,    0,    0,  384,  380,

      381,  375,    0,  364,  375,  365,  359,    0,    0,  362,
      353,    0,  110,  366,  350,  353,  344,  352,  336,  332,
      322,  481,    0,    0,  178,  189,  305,    0,  481,  481,
        0,  188,  481,  481,  192,  199,  481,  481,  481,  481,
      481,  481,  481,  481,    0,    0,  481,  211,  215,  136,
        0,  481,  307,    0,    0,    0,    0,    0,  311,  295,
        0,  303,    0,  290,    0,    0,    0,   83,  288,  291,
      280,  238,  238,  230,  236,  231,  228,  211,  222,  234,
      234,  233,  202,    0,  237,  244,  228,    0,    0,  226,
      219,    0,  229,  198,  213,  206,  201,  192,    0,  191,

        0,    0,  194,  184,  243,  263,  481,    0,  481,    0,
      153,    0,    0,    0,    0,  146,  158,  137,  118,    0,
        0,    0,  264,  481,  481,  124,  107,    0,    0,    0,
      105,   42,    0,  481,  279,  289,  299,  309,  319,  322,
      326,  332,  338,  348,  358,  368,  378,  388,  394,  400,
      406,  409,  415,  421,  431,  437,  443,  453,  459,  465
    } ;

static yyconst short int yy_def[261] =
    {   0,
      234,    1,  235,  235,  236,  236,  237,  237,  238,  238,
      239,  239,  239,  239,  234,  234,  234,  234,  234,  234,
      240,  234,  234,  234,  234,  234,  234,  234,  234,  234,
      234,  234,  234,  234,  234,  234,  234,  241,  242,  234,
      234,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  234,  234,  234,
      244,  245,  246,  247,  234,  234,  248,  234,  248,  234,
      234,  249,  250,  234,  234,  234,  234,  234,  234,  234,
      234,  234,  234,  234,  234,  234,  251,  234,  234,  234,
      234,  234,  234,  252,  253,  254,  242,  243,  243,  243,

      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  234,  244,  245,  234,  246,  255,  247,  234,  234,
      248,  248,  234,  234,  234,  234,  234,  234,  234,  234,
      234,  234,  234,  234,  249,  250,  234,  234,  234,  234,
      251,  234,  234,  256,  257,  253,  254,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  234,  234,  234,
      258,  248,  234,  259,  234,  234,  234,  256,  257,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,

      243,  243,  243,  243,  234,  234,  234,  248,  234,  260,
      234,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  234,  234,  234,  243,  243,  243,  243,  243,
      243,  243,  243,    0,  234,  234,  234,  234,  234,  234,
      234,  234,  234,  234,  234,  234,  234,  234,  234,  234,
      234,  234,  234,  234,  234,  234,  234,  234,  234,  234
    } ;

static yyconst short int yy_nxt[539] =
    {   0,
       16,   17,   18,   19,   20,   21,   22,   23,   24,   25,
       26,   27,   28,   29,   30,   31,   32,   33,   33,   33,
       34,   35,   36,   37,   38,   39,   39,   39,   39,   40,
       16,   41,   42,   43,   44,   45,   46,   47,   48,   42,
       42,   49,   42,   42,   50,   51,   52,   53,   54,   55,
       56,   42,   57,   42,   58,   59,   60,   65,   65,   16,
       16,   68,   68,   72,   72,   72,   72,   91,   76,  102,
       77,   78,   78,   78,   69,   69,   79,  103,  233,   92,
       66,   66,   76,  126,   77,   78,   78,   78,   70,   70,
       80,   81,  106,   82,   82,   82,   82,   76,  127,   84,

       84,   84,   77,   76,  107,   88,   88,   88,   88,  104,
      105,   85,   94,   95,   95,   95,   95,   86,  108,  110,
      116,  118,  113,  111,  109,  114,  129,  194,  119,   82,
       82,   82,   82,  117,  195,   76,   87,   77,   77,   77,
       77,   76,  232,   88,   88,   88,   88,  150,  150,  130,
      133,  168,  150,  150,  134,  169,  231,   82,   82,   82,
       82,  230,  229,  135,  136,  136,   76,  148,   84,   84,
       84,   77,  228,  149,  149,  149,  149,  137,  148,  178,
      138,  139,  149,  149,   76,  140,   88,   88,   88,   88,
      179,  141,  178,  227,  142,  226,  143,  225,  144,  154,

      154,  154,  154,  179,  182,  182,  182,  182,  183,  183,
      183,  126,  178,  182,  182,  183,  183,  183,  209,  209,
      209,  222,  185,  178,  185,  178,  127,  186,  186,  186,
      186,  149,  149,  149,  149,  205,  178,  221,  220,  219,
      149,  149,  218,  217,  205,  184,  216,  215,  205,  208,
      208,  208,  208,  186,  186,  186,  186,  205,  208,  208,
      186,  186,  186,  186,  223,  223,  214,  213,  212,  211,
      207,  204,  203,  202,  201,  200,  199,  223,  223,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   64,

       64,   64,   64,   64,   64,   64,   64,   64,   64,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   73,
      198,   73,   96,   96,  197,   96,   97,  196,  193,   97,
      192,   97,   98,  191,  190,   98,  187,   98,  123,  181,
      123,  123,  123,  123,  123,  123,  123,  123,  124,  124,
      124,  124,  124,  177,  124,  124,  124,  124,  125,  125,
      125,  125,  125,  125,  125,  125,  125,  125,  128,  128,
      128,  176,  128,  128,  128,  128,  175,  128,  131,  174,
      173,  131,  131,  131,  131,  131,  172,  131,  145,  171,

      170,  145,  167,  145,  146,  166,  165,  146,  164,  146,
      151,  163,  162,  161,  160,  151,  155,  159,  155,  156,
      158,  153,  156,  152,  156,  157,  147,  132,  157,  122,
      157,  180,  180,  180,  180,  180,  180,  180,  180,  180,
      180,  188,  121,  120,  188,  115,  188,  189,  112,  101,
      189,  100,  189,  206,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  210,   99,   93,   90,   89,  210,  224,
       83,   75,   74,   71,  224,  234,   63,   63,   16,   16,
       15,  234,  234,  234,  234,  234,  234,  234,  234,  234,
      234,  234,  234,  234,  234,  234,  234,  234,  234,  234,

      234,  234,  234,  234,  234,  234,  234,  234,  234,  234,
      234,  234,  234,  234,  234,  234,  234,  234,  234,  234,
      234,  234,  234,  234,  234,  234,  234,  234,  234,  234,
      234,  234,  234,  234,  234,  234,  234,  234
    } ;

static yyconst short int yy_chk[539] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    7,    8,    9,
       10,    9,   10,   21,   21,   21,   21,   36,   27,   46,
       27,   27,   27,   27,    9,   10,   27,   46,  232,   36,
        7,    8,   29,   63,   29,   29,   29,   29,    9,   10,
       29,   30,   48,   30,   30,   30,   30,   32,   63,   32,

       32,   32,   32,   33,   48,   33,   33,   33,   33,   47,
       47,   32,   38,   38,   38,   38,   38,   32,   49,   50,
       54,   55,   52,   50,   49,   52,   66,  168,   55,   76,
       76,   76,   76,   54,  168,   77,   32,   77,   77,   77,
       77,   78,  231,   78,   78,   78,   78,   86,   86,   66,
       70,  113,  150,  150,   70,  113,  227,   82,   82,   82,
       82,  226,  219,   70,   70,   70,   84,   82,   84,   84,
       84,   84,  218,   85,   85,   85,   85,   70,   82,  125,
       70,   70,   85,   85,   88,   70,   88,   88,   88,   88,
      126,   70,  125,  217,   70,  216,   70,  211,   70,   94,

       94,   94,   94,  126,  132,  132,  132,  132,  135,  135,
      135,  126,  178,  132,  132,  136,  136,  136,  183,  183,
      183,  204,  148,  179,  148,  178,  126,  148,  148,  148,
      148,  149,  149,  149,  149,  180,  179,  203,  200,  198,
      149,  149,  197,  196,  205,  135,  195,  194,  180,  182,
      182,  182,  182,  185,  185,  185,  185,  205,  182,  182,
      186,  186,  186,  186,  206,  223,  193,  191,  190,  187,
      181,  177,  176,  175,  174,  173,  172,  206,  223,  235,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  237,

      237,  237,  237,  237,  237,  237,  237,  237,  237,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  240,
      171,  240,  241,  241,  170,  241,  242,  169,  164,  242,
      162,  242,  243,  160,  159,  243,  153,  243,  244,  127,
      244,  244,  244,  244,  244,  244,  244,  244,  245,  245,
      245,  245,  245,  121,  245,  245,  245,  245,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  247,  247,
      247,  120,  247,  247,  247,  247,  119,  247,  248,  118,
      117,  248,  248,  248,  248,  248,  116,  248,  249,  115,

      114,  249,  111,  249,  250,  110,  107,  250,  106,  250,
      251,  105,  104,  102,  101,  251,  252,  100,  252,  253,
       99,   92,  253,   90,  253,  254,   81,   69,  254,   59,
      254,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  256,   57,   56,  256,   53,  256,  257,   51,   45,
      257,   44,  257,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  259,   43,   37,   35,   34,  259,  260,
       31,   26,   22,   18,  260,   15,    6,    5,    4,    3,
      234,  234,  234,  234,  234,  234,  234,  234,  234,  234,
      234,  234,  234,  234,  234,  234,  234,  234,  234,  234,

      234,  234,  234,  234,  234,  234,  234,  234,  234,  234,
      234,  234,  234,  234,  234,  234,  234,  234,  234,  234,
      234,  234,  234,  234,  234,  234,  234,  234,  234,  234,
      234,  234,  234,  234,  234,  234,  234,  234
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
char *yytext;
#line 1 "lexic.flex"
#define INITIAL 0
#line 2 "lexic.flex"

#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <locale.h>
#include "grammatic_struct.h"
#include "grammatic.tab.h"
#include "treePrint.h"

extern char* yytext;
extern int yylineno;
extern int yyparse(void);
void yyerror(char *err);
FILE* tree;
#define YY_NEVER_INTERACTIVE 1
#define ONE_COMMENT 1

#define MANY_COMMENTS 2

#define SIMPLE_STRING 3

#define DIF_STRING 4

#define METHOD 5

#define METHOD_NAME 6

#line 634 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 32 "lexic.flex"




int _int;                   //output int
float _float;               //output float
int len;                    // strings length
int i;                      // counter
char tmp[100] = "";         // для перевода числа из двоичной в десятичную систему счисления
char comment[10000] = "";   // comment
char text[10000] = "";      // comment
char strings[1000] = "";	// for output
char s[2];
struct Name_and_type_var *tempVar;	// переменная для записи разобранной переменной


#line 798 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 235 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 481 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 48 "lexic.flex"
{
	return NL;
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 52 "lexic.flex"
{    
	//printf("Операция: %s\n", yytext);
	return '+';
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 56 "lexic.flex"
{
	//printf("Операция: %s\n", yytext);
	return '.';
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 60 "lexic.flex"
{
    //printf("Операция: %s\n", yytext);
	return '-';
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 64 "lexic.flex"
{
    //printf("Операция: %s\n", yytext);
	return '*';
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 68 "lexic.flex"
{
    //printf("Операция: %s\n", yytext);
	return '/';
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 72 "lexic.flex"
{
    //printf("Операция: %s\n", yytext);
	return '=';
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 76 "lexic.flex"
{
    //printf("Операция: %s\n", yytext);
	return ADDASSIGN;
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 80 "lexic.flex"
{
    //printf("Операция: %s\n", yytext);
	return SUBASSIGN;
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 84 "lexic.flex"
{
    //printf("Операция: %s\n", yytext);
	return MULASSIGN;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 88 "lexic.flex"
{
    //printf("Операция: %s\n", yytext);
	return DIVASSIGN;
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 92 "lexic.flex"
{
     //printf("Операция: %s\n", yytext);
	 return '>';
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 96 "lexic.flex"
{
    //printf("Операция: %s\n", yytext);
	return MOREEQ;
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 100 "lexic.flex"
{
    //printf("Операция: %s\n", yytext);
	return '<';
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 104 "lexic.flex"
{
	//printf("Операция: %s\n", yytext);
	return LESSEQ;
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 108 "lexic.flex"
{
	//printf("Операция: %s\n", yytext);
	return LESSMORE;
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 112 "lexic.flex"
{
	//printf("Операция: %s\n", yytext);
	return NEQ;
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 116 "lexic.flex"
{
	//printf("Операция: %s\n", yytext);
	return EQ;
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 120 "lexic.flex"
{
	//printf("Операция: %s\n", yytext);
	return ORWORD;
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 124 "lexic.flex"
{
	//printf("Операция: %s\n", yytext);
	return ANDWORD;
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 128 "lexic.flex"
{
    //printf("Операция: %s\n", yytext);
	return '[';
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 132 "lexic.flex"
{
    //printf("Операция: %s\n", yytext);
	return ']';
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 136 "lexic.flex"
{
    //printf("Операция: %s\n", yytext);
	return '(';
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 140 "lexic.flex"
{
    //printf("Операция: %s\n", yytext);
	return ')';
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 144 "lexic.flex"
{
    //printf("Операция: %s\n", yytext);
	return '{';
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 148 "lexic.flex"
{
    //printf("Операция: %s\n", yytext);
	return '}';
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 152 "lexic.flex"
{
    //printf("Операция: %s\n", yytext);
	return '!';
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 156 "lexic.flex"
{
    //printf("Операция: %s\n", yytext);
	return ':';
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 160 "lexic.flex"
{
    //printf("Операция: %s\n", yytext);
	return ',';
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 164 "lexic.flex"
{
	//printf("Операция: %s\n", yytext);
	return THREEPOINT;
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 168 "lexic.flex"
{
	//printf("Операция: %s\n", yytext);
	return TWOPOINT;
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 173 "lexic.flex"
{
	yylval.int_const = atoi("0");
	return INT;
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 178 "lexic.flex"
{
	//printf("Целочисленная константа: %s \n", yytext);
	yylval.int_const  = atoi(yytext);
	return INT;
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 184 "lexic.flex"
{
	sscanf(yytext, "%g", &_float);
	//printf("Дробная константа: %g \n", _float);
	yylval.float_const  = _float;
	return FLOAT;
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 191 "lexic.flex"
{
	sscanf(yytext, "%x", &_int);
	//printf("Шестнадцатеричная константа: %d \n", _int);
	yylval.int_const = _int;
	return INT;
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 198 "lexic.flex"
{
	sscanf(yytext, "%o", &_int);
	//printf("Восьмеричная константа: %d \n", _int);
	yylval.int_const = _int;
	return INT;
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 205 "lexic.flex"
{
	tmp[0] = 0;
	_int= 0;

    strcat(tmp, &yytext[2]);
    len = strlen(tmp);
    for(i = 0; i < len; i++) {
    	if(tmp[i] == '1') {
    		_int += 1 << len -1 -i;
        }
    }
    //printf("Двоичная константа: %d \n", _int);
	yylval.int_const = _int;
	return INT;
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 221 "lexic.flex"
{
    //printf("Ключевое слово: %s\n", yytext);
	return NIL;
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 225 "lexic.flex"
{
    //printf("Ключевое слово: %s\n", yytext);
	return DEF;
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 229 "lexic.flex"
{
    //printf("Ключевое слово: %s\n", yytext);
	return SELF;
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 233 "lexic.flex"
{
    //printf("Ключевое слово: %s\n", yytext);
	return NOT;
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 237 "lexic.flex"
{
    printf("Ключевое слово: %s\n", yytext);
	return SUPER;
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 241 "lexic.flex"
{
    //printf("Ключевое слово: %s\n", yytext);
	return WHILE;
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 245 "lexic.flex"
{
    //printf("Ключевое слово: %s\n", yytext);
	return UNTIL;
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 249 "lexic.flex"
{
    //printf("Ключевое слово: %s\n", yytext);
	return FOR;
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 253 "lexic.flex"
{
    //printf("Ключевое слово: %s\n", yytext);
	return THEN;
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 257 "lexic.flex"
{
    //printf("Ключевое слово: %s\n", yytext);
	return DO;
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 261 "lexic.flex"
{
    //printf("Ключевое слово: %s\n", yytext);
	return IF;
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 265 "lexic.flex"
{
    //printf("Ключевое слово: %s\n", yytext);
	return ELSE;
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 269 "lexic.flex"
{
    //printf("Ключевое слово: %s\n", yytext);
	return IN;
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 273 "lexic.flex"
{
    //printf("Ключевое слово: %s\n", yytext);
	return END;
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 277 "lexic.flex"
{
    //printf("Ключевое слово: %s\n", yytext);
	return RETURN;
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 281 "lexic.flex"
{
    //printf("Ключевое слово: %s\n", yytext);
	return PUBLIC;
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 285 "lexic.flex"
{
    //printf("Ключевое слово: %s\n", yytext);
	return PRIVATE;
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 289 "lexic.flex"
{
    //printf("Ключевое слово: %s\n", yytext);
	return ORWORD;
}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 293 "lexic.flex"
{
    //printf("Ключевое слово: %s\n", yytext);
	return ANDWORD;
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 297 "lexic.flex"
{
    //printf("Ключевое слово: %s\n", yytext);
	return PROTECTED;
}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 301 "lexic.flex"
{
    //printf("Ключевое слово: %s\n", yytext);
	return BREAK;
}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 305 "lexic.flex"
{
    return CLASS;
}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 309 "lexic.flex"
{
	//printf("Ключевое слово: %s\n", yytext);
	yylval.bool_const = 0;
	return BOOL;
}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 314 "lexic.flex"
{
	//printf("Ключевое слово: %s\n", yytext);
	yylval.bool_const = 1;
	return BOOL;
}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 320 "lexic.flex"
{
	//printf("Метод для работы с консолью: %s\n", yytext);
	return PRINT;
}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 325 "lexic.flex"
{
	//printf("Метод для работы с консолью: %s\n", yytext);
	return P;
}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 330 "lexic.flex"
{
	//strcpy(text, yytext);
	//printf("Константа: %s\n", text);
	tempVar = (struct Name_and_type_var*)malloc(sizeof(struct Name_and_type_var));
	tempVar->name_var = (char*)malloc(strlen(yytext));
	strcpy(tempVar->name_var, yytext);		// записываем имя переменной
	tempVar->type = CONSTANT;			// записываем тип доступа
	yylval.var = tempVar;
	return CONST;
}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 341 "lexic.flex"
{
	//strcpy(text, yytext);
	//printf("Идентификатор: %s\n", text);
	tempVar = (struct Name_and_type_var*)malloc(sizeof(struct Name_and_type_var));
	tempVar->name_var = (char*)malloc(strlen(yytext));
	strcpy(tempVar->name_var, yytext);		// записываем имя переменной
	tempVar->type = LOCALVAR;			// записываем тип доступа
	yylval.var = tempVar;
	return ID;
}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 352 "lexic.flex"
{
	//strcpy(text, &yytext[1]);
	//printf("Глобальная переменная: %s\n", text);
	tempVar = (struct Name_and_type_var*)malloc(sizeof(struct Name_and_type_var));
	tempVar->name_var = (char*)malloc(strlen(yytext));
	strcpy(tempVar->name_var, yytext);		// записываем имя переменной
	tempVar->type = GLOBALVAR;			// записываем тип доступа
	yylval.var = tempVar;
	return ID;
}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 363 "lexic.flex"
{
	//strcpy(text, &yytext[1]);
	//printf("Переменная объекта: %s\n", text);
	tempVar = (struct Name_and_type_var*)malloc(sizeof(struct Name_and_type_var));
	tempVar->name_var = (char*)malloc(strlen(yytext));
	strcpy(tempVar->name_var, yytext);		// записываем имя переменной
	tempVar->type = OBJECTVAR;			// записываем тип доступа
	yylval.var = tempVar;
	return ID;
}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 374 "lexic.flex"
{
	//strcpy(text, &yytext[2]);
	//printf("Переменная класса: %s\n", text);
	tempVar = (struct Name_and_type_var*)malloc(sizeof(struct Name_and_type_var));
	tempVar->name_var = (char*)malloc(strlen(yytext));
	strcpy(tempVar->name_var, yytext);		// записываем имя переменной
	tempVar->type = CLASSVAR;			// записываем тип доступа
	yylval.var = tempVar;
	return ID;
}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 385 "lexic.flex"
BEGIN(MANY_COMMENTS);
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 387 "lexic.flex"
{
	strcat(comment, yytext);
}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 391 "lexic.flex"
{
    strcat(comment, yytext);
}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 395 "lexic.flex"
{
    strcat(comment, yytext);
}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 399 "lexic.flex"
{
    strcat(comment, yytext);
}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 403 "lexic.flex"
{
	strcat(comment,yytext);
	comment[strlen(comment)-4] = 0;
	//printf("Многострочный комментарий: %s\n",comment);
    yylval.string_const = (char*)malloc(sizeof(char)*strlen(comment));
	strcpy(yylval.string_const, comment);
	comment[0] = 0;
	BEGIN(INITIAL);
	return STRING;
}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 414 "lexic.flex"
BEGIN(ONE_COMMENT);
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 416 "lexic.flex"
{
	strcat(comment, yytext); 
	//printf("Однострочный комментарий: %s",comment);
    yylval.string_const = (char*)malloc(sizeof(char)*strlen(comment));
	strcpy(yylval.string_const, comment);
	comment[0] = 0;
	BEGIN(INITIAL);
	return STRING;
}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 426 "lexic.flex"
{
	BEGIN(SIMPLE_STRING);
}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 430 "lexic.flex"
{
    strcat(strings, yytext);
}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 434 "lexic.flex"
{
	strcat(strings, "'");
}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 438 "lexic.flex"
{
    strcat(strings, "\\");
}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 442 "lexic.flex"
{
	//printf("Строковая константа: %s\n", strings);
    yylval.string_const = (char*)malloc(sizeof(char)*strlen(strings));
	strcpy(yylval.string_const,strings);	// копируем возвращаемое значение
	strings[0] = 0;
	BEGIN(INITIAL); 
	return STRING;
}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 451 "lexic.flex"
{
	BEGIN(DIF_STRING); 
}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 455 "lexic.flex"
{
	strcat(strings, yytext);
}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 459 "lexic.flex"
{
    sscanf(yytext+1,"%o",s);
	strcat(strings, s);
}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 464 "lexic.flex"
{
    sscanf(yytext+1,"%x",s);
	strcat(strings, s);
}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 469 "lexic.flex"
{
	strcat(strings, yytext);
}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 472 "lexic.flex"
{
	strcat(strings, yytext);
}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 475 "lexic.flex"
{
	strcat(strings, yytext);
}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 478 "lexic.flex"
{
	strcat(strings, yytext);
}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 481 "lexic.flex"
{
	strcat(strings, yytext);
}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 484 "lexic.flex"
{
	strcat(strings, yytext);
}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 487 "lexic.flex"
{
	strcat(strings, yytext);
}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 490 "lexic.flex"
{
	strcat(strings, yytext);
}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 493 "lexic.flex"
{
	strcat(strings, yytext);
}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 496 "lexic.flex"
{
	strcat(strings, yytext);
}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 499 "lexic.flex"
{
	//printf("Строковая константа: %s\n", strings);
    yylval.string_const = (char*)malloc(sizeof(char)*strlen(strings));
	strcpy(yylval.string_const, strings);	// копируем возвращаемое значение
	strings[0] = 0;
	BEGIN(INITIAL);
	return STRING;
}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 507 "lexic.flex"
{	
	return DOUBLECOLON;
}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 511 "lexic.flex"
ECHO;
	YY_BREAK
#line 1710 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(ONE_COMMENT):
			case YY_STATE_EOF(MANY_COMMENTS):
			case YY_STATE_EOF(SIMPLE_STRING):
			case YY_STATE_EOF(DIF_STRING):
			case YY_STATE_EOF(METHOD):
			case YY_STATE_EOF(METHOD_NAME):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a singled characater, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 235 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 235 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	*yy_state_ptr++ = yy_current_state;
	yy_is_jam = (yy_current_state == 234);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yytext_ptr = yy_c_buf_p;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						{
						yy_c_buf_p =
						yytext_ptr + YY_MORE_ADJ;
						return EOF;
						}

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;
					break;

				case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
					YY_FATAL_ERROR(
					"unexpected last match in yyinput()" );
#else
					YY_FATAL_ERROR(
					"unexpected last match in input()" );
#endif
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *str )
#else
YY_BUFFER_STATE yy_scan_string( str )
yyconst char *str;
#endif
	{
	int len;
	for ( len = 0; str[len]; ++len )
		;

	return yy_scan_bytes( str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n - YY_MORE_ADJ; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 511 "lexic.flex"


void yyerror(char *err) {
   printf("%s on line %d - %s\n", err, yylineno, yytext);
}

int main(int argc, char* argv[]) {
    char str[100] = "";
	setlocale(LC_CTYPE, ".1251");
    
    yyin = fopen("test.rb", "r+");
	fseek(yyin, -1, SEEK_END);
    fscanf(yyin, "%s", str);
    if(strcmp(str, "")) {
        fprintf(yyin, "\n");
    }
    fclose(yyin);

    yyin = fopen("test.rb", "r");
	yyparse();
	tree=freopen("codetree.xml","w",stdout);
	tree_print();
	fclose(tree);
	fclose(yyin);
	system("pause");
    return 0;
}